### ISSUE TITLE
Uploading Avatar Doesn't Show Updated Avatar Immediately

### ISSUE THREAD

**Issue by zicklag** [muni-town/weird#166]
It seems like sometimes the browser caches the avatar after setting it, and shows the old generated one, even thought it did update for some reason.

We should try to reproduce and fix if possible. I think this issue was noticed in Safari. ( Is that right @EstebanBorai? )

**Comment by EstebanBorai** [comment]
> It seems like sometimes the browser caches the avatar after setting it, and shows the old generated one, even thought it did update for some reason.
> 
> We should try to reproduce and fix if possible. I think this issue was noticed in Safari. ( Is that right @EstebanBorai? )

Yep!

**Comment by zicklag** [comment]
Fixed in 2a3b32c32b117a205bc7a7cb260dcbb1d1b6dd7c
