### ISSUE TITLE
MVP v0.3.0

### ISSUE THREAD

**Issue by erlend-sh** [muni-town/weird#2]
### MVP (v0.3)

- [x] Signup/Login
- [x] Link lists
- [x] Static site renderer
- [x] hosted service
- [x] scraper
- [x] edit in-place
- [x] certbot
- [x] Taking names integration
- [x] Social site importer
- [x] automated profiles (github, linkedin..)
- [x] Domains as usernames
- [x] Wiki pages & primitive revisions ( everybody can edit )
- [x] Original theme
- [x] Billing integration

**Comment by zicklag** [comment]
Is this done now and we should make another v0.2.0 issue?

**Comment by erlend-sh** [comment]
Let’s just edit this to be for v0.3 as a whole, since this is about the ‘MVP release’.

**Comment by zicklag** [comment]
This is done!! 🎉
