### ISSUE TITLE
Different avatar

### ISSUE THREAD

**Issue by erlend-sh** [muni-town/weird#207]
For some reason the avatars are not the same:

![IMG_2531](https://github.com/user-attachments/assets/ed7fcaae-eb54-41c1-b0a5-3a04a2e48b7f)
![IMG_2532](https://github.com/user-attachments/assets/05e4da57-1d72-4e10-beda-4af0c331af6c)

**Comment by zicklag** [comment]
Fixed in 2a3b32c32b117a205bc7a7cb260dcbb1d1b6dd7c
