### ISSUE TITLE
stuck at password entry

### ISSUE THREAD

**Issue by joepio** [muni-town/weird#210]
After running `just setup` and `just dev`, I tried to register and opened the `smpt4dev` interface to open the password set link. I can't get a password to pass the ` ⭕ Not one of your 3 recently used passwords` check.

<img width="687" alt="Screenshot 2024-10-15 at 14 41 18" src="https://github.com/user-attachments/assets/97c51b1d-cdfa-488c-894e-e3f6be5344a3">

Obviously, I haven't tried a bunch of random strings. I just can't get to click `set password`.

Cool project btw :) very interesting

**Comment by zicklag** [comment]
Fixed in [db31b8b](https://github.com/muni-town/weird/commit/db31b8b68105b06c0d036749b50a551fb5866d6e).
