### ISSUE TITLE
Merge title and slug

### ISSUE THREAD

**Issue by erlend-sh** [muni-town/weird#211]
![IMG_2539](https://github.com/user-attachments/assets/a70e32ed-fa5d-4ddf-9ca1-fb875e0f3dbc)

You should only have to edit the Title by default. Slug is auto typed from the title.

Slug will still be editable but it should be heavily deemphasized.

*side note:* we don’t need any of the ‘Click to edit’ buttons (I know I had smt like that in my mock-ups, but they were just descriptive), let’s remove them.

All we want is any kind of clear indicator up top that says some equivalent of ‘this page is editable btw!’.

**Comment by harshmangalam** [comment]
https://github.com/muni-town/weird/pull/234
