### ISSUE TITLE
Automated DNS guidance

### ISSUE THREAD

**Issue by erlend-sh** [muni-town/weird#223]
![IMG_2564](https://github.com/user-attachments/assets/3e5a88a4-cce3-47b4-98c1-59b0b7224979)

This could probably be done in reverse.

1. Enter domain name
2. Receive instructions for that type of domain name.

**Comment by zicklag** [comment]
Implemented in 2a3b32c32b117a205bc7a7cb260dcbb1d1b6dd7c.
