### ISSUE TITLE
Weird.one frontpage

### ISSUE THREAD

**Issue by erlend-sh** [muni-town/weird#36]
We need a sparse but eye-catching landing page to greet our earliest adopters. These visitors will be preloaded with some context when they arrive on our site, so we don't _yet_ have to worry about perfectly pitching Weird under the assumption of zero prior knowledge.

The page should cover:

- Weird speed intro (header + tagline)
- Signup prompt ([biolink](https://bio.link/) url-claimer style for now?)
- Further reading (info boxes and links to dedicated explainers for Big Three)
- [Weird brand identity](https://github.com/commune-os/weird/discussions/21)

---

First draft:

# Weird

*Your home on the internet* (cybernet/hinterweb/indieweb)
[flash intermittently between the default *internet* and any of the other terms, in their own unique style.]
*Your internet passport*

[sign up]

Weird is..
- your personal space in the web; magic website creation.
- a public ID card; independent 'social sign-in' for the indie web.
- (..which together enable) a network of shared purpose

---

I'm playing around with a few different tag lines. It's easy enough to capture the essence of 'ID card' + 'social sign-in'. It's hard to also hint at the NoSP in a one-liner, but it may not be necessary, since the Weird experience doesn't *start* there.

**Comment by hnb-ku** [comment]
Thanks for the writeup!

Breaking thins down for my own purposes

- [ ] skeleton for the landing page
- [ ] copy
- [ ] branding and Weird assets
- [ ] URL-claimer work
- [ ] initial pass on the "your own page"

**Comment by erlend-sh** [comment]
For copy: solicit anything you'd like from me, but feel free to play around with your own ideas as you see fit.

**Comment by erlend-sh** [comment]
Here’s an update on the imagined page layout. I think what I laid out in the ‘First draft’ above is gonna be the secondary section of the site. The primary (first) will go more as follows:

- - -

# Weird

***Say goodbye to the old web..***

[big mashup of mainstream services and their infamous “features” (a tweet, a fb login etc.), but we rewrite their standard copy with ‘honest advertising’.]

***Say hello, again, to the weird web..***

[mashup up all the awesome indieweb services and spaces out there (codeberg, Omnivore, Supabase, Mastodon etc.), all connecting to a Weird account + website.

- - -

Here’s a mock-up, taken at night so text isn’t super clear, but you have the same text written above, and I quite liked the lighting:

![IMG_2374](https://github.com/commune-os/weird/assets/583842/0fe67444-c587-4bc2-a729-9b38b9a915dc)

Here’s an earlier mock-up that I did, which was superceded by the above. But it’s still a good illustration of the he kind of ‘honest advertising’ we wanna do in the first illustration.
![IMG_2382](https://github.com/commune-os/weird/assets/583842/53ac43e4-7923-4788-97b9-e72fedf5e0e5)

I will provide higher definition mock-ups of the two illustrations in the following days. I can get started on this sooner rather than later if I’m provided with a mashup-board of mainstream-socials UX screens for inspiration 👀

**Comment by erlend-sh** [comment]
## Subpage: Magic website creator

To fully inhabit the World Wide Web (*interwebs* for fun, or just *the web* for short), you need to create your digital self within it.

The way to do that is a personal website [why? Links1,2,3]

For a lot of us, the “simple” prospect of filling in that web page with content resents an insurmountable [writer’s block](https://en.wikipedia.org/wiki/Writer%27s_block).

Thankfully, Wikipedia’s Irene Clark offers plenty of coping strategies, one of which we’re going all-in on:

Making lists!!! (three exclamation points make a vertical list icon; maybe we can play with that graphic)

Since we’re on the interwebs, the best things to list are web-links.

..like your existing web identities 

- mastodon
- github
- matrix

..or it could just be your three favorite movies

- Twilight
- Titanic
- Tombstone

Whatever you’ve listed, you’ve done it! You told us something about yourself.

Now, not only are you taking up a bit of space on the web, as you should. You’ve also got your very own **web-passport** 🪪

**Comment by erlend-sh** [comment]
Backups of our latest copy, which will be phased out soon:

### Magic Website Creator

To fully inhabit the World Wide Web you need to create your digital self within it.

For a lot of us, the “simple” prospect of filling in that web page with content presents an insurmountable [writer’s block](https://en.wikipedia.org/wiki/Writer%27s_block).

That’s why we start with link lists as a primitive building block. Make a list of 1, 3 or however many links that say something, anything, about you.

Whatever you’ve listed, you’ve done it! You told us something about your self, and with that you are taking up a bit of space on the web, as you should.

### Web Passports

Weird is the “Google-login” button of the alt-web. A [web of the people](https://blog.erlend.sh/web-of-the-people), powered by people's websites instead of those pesky totalitarian mega-platforms.

By making - or merely connecting - your website with Weird you will soon be able to access and interact with the small, open and indie web just as easily as the regular web works today. Same conveniences, without the dark patterns, spying and data theft.
