### ISSUE TITLE
Add Link Lists

### ISSUE THREAD

**Issue by zicklag** [muni-town/weird#91]
Right now we have the backend implemented for user lists, which are like link lists, but we don't have a UI for it.

There is more discussion on links in https://github.com/commune-os/weird/discussions/64. I haven't fully digested the technical implications. We may want to wait on link lists in the profiles until we nail down a broader concept of how we want to approach links in general from a technical perspective.

**Comment by erlend-sh** [comment]
I’m thinking the best default for links entry is to start with just a singular form: 

![IMG_2530](https://github.com/user-attachments/assets/867339a1-c9ce-4be3-9106-cd90f3efecba)

We just need whatever the JS/Svelte equivalent of this is:

https://github.com/EstebanBorai/link-preview

The title box should only appear *after* a URL has been entered. That title box should appear *above* the URL box, filled in with whatever title (editable) we could grab from the URL.

We’ll pull in whatever other meta-data that’s available about the URL and make a nice [onebox](https://meta.discourse.org/t/configuring-and-troubleshooting-oneboxes/239715) out of it.

https://github.com/discourse/onebox/blob/main/README.md

Eventually it should all be editable (and users can choose between compact/rich/.. link styles) but we’re starting with just URL —> Title.

**Comment by harshmangalam** [comment]
This issues have been resolved in  https://github.com/muni-town/weird/pull/214 PR .
