### ISSUE TITLE
Investigate a Streamlined Connection Between Weird Core and SvelteKit.

### ISSUE THREAD

**Issue by zicklag** [muni-town/weird#92]
This is an exploratory task to see if there is a better way than a REST API to connect SvelteKit to the Weird core.

Right now we have the Weird core library which is implemented in Rust and uses Iroh, and we have a wrapper around that core library that exposes a Rest API for the specific needs of the SvelteKit app. I would like to be able remove this "hand-holding" that the REST API does for the SvelteKit app, and be able to more directly access the Weird core graph functionality.

I'm thinking of something along the lines of a JSON-RPC instead of REST, or maybe a QUIC RPC client in SvelteKit if that's possible? 

Another possibility is to use a Node.js extension, so that it can be used as a JS library. One minor annoyance to that is that it would probably increase CI times for the frontend, which is nice to be able to quickly deploy right now, when there are no backend changes.

Still, if that's a better development experience that's probably a better option.

**Comment by erlend-sh** [comment]
Closed by Leaf #122 ?

**Comment by zicklag** [comment]
Oh, yeah! :partying_face:
